# Generated by Django 4.1.4 on 2023-09-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('exam', '0003_classallotments'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='allot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_allot', to='exam.classallotments'),
        ),
        migrations.AlterField(
            model_name='allot',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allots_exam', to='exam.exams'),
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_allotments_classroom', to='classroom.classes'),
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_allotments', to='exam.exams'),
        ),
    ]
