# Generated by Django 4.1.4 on 2023-09-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('exam', '0004_exams_allot_alter_allot_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classallotments',
            name='seatcolumns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classes'),
        ),
        migrations.AddField(
            model_name='classallotments',
            name='seatrows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classroom.classes'),
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classallotclassroom', to='classroom.classes'),
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classallot', to='exam.exams'),
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classroom.classes'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='allot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examsallot', to='exam.classallotments'),
        ),
    ]
