# Generated by Django 4.1.4 on 2023-09-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('exam', '0005_classallotments_seatcolumns_classallotments_seatrows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotments',
            name='seatcolumns',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='seatrows',
        ),
        migrations.AlterField(
            model_name='classallotments',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classes'),
        ),
    ]
