# Generated by Django 4.1.4 on 2023-09-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_classallotments_seatcolumns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotments',
            name='strength',
        ),
    ]
