# Generated by Django 4.1.4 on 2023-09-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_classallotments_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotments',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='department',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='classallotments',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='allot',
        ),
        migrations.DeleteModel(
            name='Allot',
        ),
        migrations.DeleteModel(
            name='ClassAllotments',
        ),
    ]
