# Generated by Django 4.1.4 on 2023-09-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_allot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allot',
        ),
    ]
