# Generated by Django 4.1.4 on 2023-09-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_exams_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='staff',
        ),
    ]
