# Generated by Django 4.1.4 on 2023-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notificationsstaff',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notificationsstaff',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
