# Generated by Django 4.1.4 on 2023-10-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_studentnotifications_staffnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotifications',
            name='usertype',
            field=models.CharField(default='', max_length=500),
        ),
    ]
