# Generated by Django 4.1.4 on 2023-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_staffnotifications_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='usertype',
            field=models.CharField(default='', max_length=500),
        ),
    ]
