# Generated by Django 4.1.4 on 2023-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_add_work',
            name='message',
            field=models.CharField(default='Not Updated', max_length=500),
        ),
    ]
