# Generated by Django 4.1.4 on 2023-10-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0002_student_add_work_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add_work',
            name='update_status',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
    ]
