# Generated by Django 4.1.4 on 2023-10-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0003_alter_student_add_work_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_add_work',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
