# Generated by Django 4.1.4 on 2023-10-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0004_student_add_work_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_add_work',
            name='files',
        ),
    ]
