# Generated by Django 4.1.4 on 2023-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0005_remove_student_add_work_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_add_work',
            name='files',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
