# Generated by Django 4.1.4 on 2023-10-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0006_student_add_work_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_add_work',
            old_name='files',
            new_name='filess',
        ),
    ]
