# Generated by Django 4.1.4 on 2023-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0007_rename_files_student_add_work_filess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add_work',
            name='filess',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
