# Generated by Django 4.1.4 on 2023-10-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0008_alter_student_add_work_filess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_add_work',
            old_name='filess',
            new_name='files',
        ),
    ]
