# Generated by Django 4.1.4 on 2023-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0009_rename_filess_student_add_work_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add_work',
            name='update_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
