# Generated by Django 4.1.4 on 2023-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwork', '0010_alter_student_add_work_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add_work',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
