# Generated by Django 4.1.4 on 2023-08-30 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='respondedby',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
