# Generated by Django 4.1.4 on 2023-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
