# Generated by Django 4.1.4 on 2023-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_register_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
