# Generated by Django 4.1.4 on 2023-09-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_register_status_alter_register_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='examstatus',
            field=models.IntegerField(default=0),
        ),
    ]
