# Generated by Django 4.1.4 on 2023-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_register_examstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='regno',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
