# Generated by Django 4.1.4 on 2023-09-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_register_regno_alter_register_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('username', 'regno')},
        ),
    ]
