# Generated by Django 4.1.4 on 2023-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_work',
            name='message',
            field=models.CharField(default='Not Updated', max_length=500),
        ),
        migrations.AlterField(
            model_name='add_work',
            name='update_status',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
    ]
