# Generated by Django 4.1.4 on 2023-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0002_alter_add_work_message_alter_add_work_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_work',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
