# Generated by Django 4.1.4 on 2023-10-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0003_add_work_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_work',
            name='files',
        ),
        migrations.AddField(
            model_name='add_work',
            name='filess',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
