# Generated by Django 4.1.4 on 2023-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0004_remove_add_work_files_add_work_filess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_work',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='add_work',
            name='update_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
