# Generated by Django 4.1.4 on 2023-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0005_alter_add_work_message_alter_add_work_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_work',
            name='status',
            field=models.CharField(default='', max_length=500),
        ),
    ]
