# Generated by Django 4.1.4 on 2023-10-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0006_alter_add_work_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_work',
            old_name='filess',
            new_name='files',
        ),
    ]
