# Generated by Django 4.1.4 on 2023-10-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0009_add_work_delete_addwork_delete_statusupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_status', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
                ('files', models.FileField(default='', upload_to='')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffwork.add_work')),
            ],
        ),
    ]
