# Generated by Django 4.1.4 on 2023-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classallotments',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
