# Generated by Django 4.1.4 on 2023-09-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0004_alter_classallotments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotments',
            name='status',
        ),
    ]
