# Generated by Django 4.1.4 on 2023-09-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0005_remove_classallotments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAllotmentsDupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classallotments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classallotment.classallotments')),
            ],
        ),
    ]
