# Generated by Django 4.1.4 on 2023-09-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0006_classallotmentsdupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classallotmentsdupe',
            name='classallotments',
        ),
        migrations.DeleteModel(
            name='ClassAllotments',
        ),
        migrations.DeleteModel(
            name='ClassAllotmentsDupe',
        ),
    ]
