# Generated by Django 4.1.4 on 2023-09-19 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
        ('classallotment', '0009_allot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allot',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='allot',
            name='room',
        ),
        migrations.RemoveField(
            model_name='allot',
            name='rows',
        ),
        migrations.AddField(
            model_name='allot',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classallotment.classallotments'),
        ),
        migrations.AddField(
            model_name='allot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='allot',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allot',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subjects'),
        ),
        migrations.AlterField(
            model_name='allot',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
