# Generated by Django 4.1.4 on 2023-09-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0010_remove_allot_columns_remove_allot_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='allot',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='allot',
            name='subject',
        ),
        migrations.AddField(
            model_name='allot',
            name='column',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allot',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
