# Generated by Django 4.1.4 on 2023-09-21 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classallotment', '0011_remove_allot_date_remove_allot_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allot',
            name='student',
        ),
        migrations.AddField(
            model_name='allot',
            name='student',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
