# Generated by Django 4.1.4 on 2023-09-21 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classallotment', '0012_remove_allot_student_allot_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allot',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
