# Generated by Django 4.1.4 on 2023-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0013_alter_allot_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classallotments',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
