# Generated by Django 4.1.4 on 2023-09-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classallotment', '0014_classallotments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classallotments',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
